apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pythonapp-http
spec:
  hosts:
    - "*"
  gateways:
  - pythonapp-gateway
  http:
  - match:
    - uri:
        prefix: /v2
    route:
    - destination:
        host: pythonapp
        subset: version2
        port:
          number: 5000
  - match:
    - uri :
        prefix: /v1
    rewrite:
      uri: /
    route:
    - destination:
        host: pythonapp
        subset: version1
        port:
          number: 5000
