apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pythonapp-destination-rule
spec:
  host: pythonapp
  subsets:
  - labels:
      version: v1
    name: version1
  - labels:
      version: v2
    name: version2
